// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ZcSaGiLUHiNYHU83ROOpbxKwjBuWavI',
    appId: '1:1016941726459:web:55aba32ef6cb9bd2e9fe5e',
    messagingSenderId: '1016941726459',
    projectId: 'borntobake-1998',
    authDomain: 'borntobake-1998.firebaseapp.com',
    storageBucket: 'borntobake-1998.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9JBFb9uILqn6O49tl1_CjXgiczK4YPmI',
    appId: '1:1016941726459:android:9d4765c3702eed0ee9fe5e',
    messagingSenderId: '1016941726459',
    projectId: 'borntobake-1998',
    storageBucket: 'borntobake-1998.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyd7sVQ6o0WOihiEdHIf95YdYasPscnTw',
    appId: '1:1016941726459:ios:f0eafbb9dd51a5a1e9fe5e',
    messagingSenderId: '1016941726459',
    projectId: 'borntobake-1998',
    storageBucket: 'borntobake-1998.firebasestorage.app',
    iosBundleId: 'com.example.born2bake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyd7sVQ6o0WOihiEdHIf95YdYasPscnTw',
    appId: '1:1016941726459:ios:f0eafbb9dd51a5a1e9fe5e',
    messagingSenderId: '1016941726459',
    projectId: 'borntobake-1998',
    storageBucket: 'borntobake-1998.firebasestorage.app',
    iosBundleId: 'com.example.born2bake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3ZcSaGiLUHiNYHU83ROOpbxKwjBuWavI',
    appId: '1:1016941726459:web:cadd37aaf1e7c3d3e9fe5e',
    messagingSenderId: '1016941726459',
    projectId: 'borntobake-1998',
    authDomain: 'borntobake-1998.firebaseapp.com',
    storageBucket: 'borntobake-1998.firebasestorage.app',
  );
}
